In [2]:
import numpy as np

In [2]:
a = 1

In [3]:
import sys
sys.executable

'/usr/bin/python3'

In [8]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [9]:
A.shape

(2, 3)

In [10]:
A.ndim

2

In [11]:
A.size

6

O .shape nos retorna o tamanho da matríz - linhas x colunas. No nosso caso a matriz __A__ tem 2 linhas e três colunas.

O .ndim diz a dimensão da matriz. A nossa matriz só tem duas simensões que são: linhas e colunas

O .size nos diz quantos elementos temos na matriz. No nosso exemplo a nossa matriz tem 6 elementos.

Agora eu vou criar uma matriz de três dimensões.

In [12]:
B = np.array([
    [
        [12, 11, 10],
        [9,8,7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [13]:
B.shape

(2, 2, 3)

In [14]:
B.ndim

3

In [15]:
B.size

12

## Como fazer slice de Matriz em numpy

In [3]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [5]:
# Aqui eu seleciono apenas a segunda linha
A[1]

array([4, 5, 6])

In [7]:
# Selecionar a segunda linha e o primeiro elemento
A[1][0]

4

In [8]:
# Também é possível fazer a mesma seleção acima da seguinte forma
A[1, 0]

4

In [9]:
# Selecionar a primeira e a segunda linha
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# Selecionar todas as linhas e as colunas de 0 a 1
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [11]:
# Redefinir a a primeira linha
A[1] = np.array([10, 10, 10])

In [12]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [13]:
# Outra forma de fazer a mesma coisa que eu fiz acima, seria fazer o seguinte
# Neste caso eu vou redefinir a terceira linha como sendo tudo 99
A[2] = 99

In [14]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Cálculos de estatística

In [20]:
a = np.array([1, 2, 3, 4])

In [21]:
# Calcula a soma da matriz
a.sum()

10

In [22]:
# Calcula a média da matriz
a.mean()

2.5

In [24]:
# Calcula o desvio padrão - standard deviation
a.std()

1.118033988749895

In [25]:
# Calcula a variação
a.var()

1.25

In [15]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [17]:
# Calcular a soma de todas as colunas da matriz. 
A.sum(axis=0)

array([12, 15, 18])

In [19]:
# Calcular a soma de todas as colunas de uma matriz
A.sum(axis=1)

array([ 6, 15, 24])

In [28]:
# Calcular a média de todas as colunas
A.mean(axis=0)

array([4., 5., 6.])

In [29]:
# Calcular a média de todas as linhas
A.mean(axis=1)

array([2., 5., 8.])

Para seleciona todas as colunas:
axis=0

Para selecionar todas as linhas:
axis=1

In [31]:
# calcular o desvio padrão de todas as colunas
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [33]:
# Calcular o desvio padrão de todas as linhas
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

A mesma lógica serve paras as outras funções estatísticas

# Importante - Um dos tópicos mais importantes de numpy

## Operações de vetorização - Em Inglês - (Broadcasting and Vectorized Operations)

Essas são operações realizadas entre arrays e arrays ou arrays e inteiros. Essas operações são otimizadas e extremamente rápidas.

In [34]:
a = np.arange(4)

In [35]:
a

array([0, 1, 2, 3])

In [36]:
# somas cada emento com o número 10
a + 10

array([10, 11, 12, 13])

In [37]:
# multiplica cada elemento do array ao número 10
a * 10

array([ 0, 10, 20, 30])

Observe que nas operações acima eu não estou modificano o array original.

Os arrays em numpy são imutáveis e se você quiser modificar o array original vocẽ vai precisar fazer o assignment da operação no array.

Veja o exemplo abaixo

In [38]:
a += 100

In [39]:
a

array([100, 101, 102, 103])

List comprehension é um exemplo muito aprecido de vetorização.
Embora a vetorização seja ainda mais eficiente e rápido.

In [40]:
l = [0, 1, 2, 3]

In [41]:
[i * 10 for i in l]

[0, 10, 20, 30]

Você também pode fazer as operações de vetorização entre array e array. 
Veja os exemplos abaixo:

In [42]:
a = np.arange(4)

In [43]:
a

array([0, 1, 2, 3])

In [44]:
b = np.array([10, 10, 10 ,10])

In [45]:
b

array([10, 10, 10, 10])

In [47]:
# Somar dois arrays
a + b

array([10, 11, 12, 13])

In [48]:
# Multiplicar dois arrays
a * b

array([ 0, 10, 20, 30])

## continuar em 1:46:21 